---
- name: Setup Docker and run container on Ansible worker (Amazon Linux 2)
  hosts: dev
  become: yes
  connection: ssh
  tasks:

    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: Add ansible to docker group
      user:
        name: ansible
        groups: docker
        append: yes

    - name: Stop existing container if present
      docker_container:
        name: webapp
        state: stopped
        force_kill: yes
      ignore_errors: yes

    - name: Remove existing container if present
      docker_container:
        name: webapp
        state: absent
      ignore_errors: yes

    - name: Remove existing image if present
      docker_image:
        name: vithran21/tomcat:v1
        source: local
        state: absent
      ignore_errors: yes

    - name: Pull Docker image 
      docker_image:
        name: vithran21/tomcat:v1
        source: pull

    - name: Run Docker container
      docker_container:
        name: webapp
        image: vithran21/tomcat:v1
        state: started
        ports:
          - "8080:8080"
